# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11cc75a237c8742d59facf31222042ef3463441b5c1143c6e5c931c5c9c10aeb61e77de3ba6ef5fb4d11c1bae004998facc441d396503d2f84ebcc61b5d09154

test:
  secret_key_base: 1fbf26d8db60f7edde47e721b36e79f393175483b49b6e7ea45309a86ada57d2aae215af8f39ed91934b100796e65d41a930ca8815a4355a918849bf3f7a584b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
